# font family lol
font_family	TerminusTTF
bold_font	TerminusTTF-Bold
italic_font	TerminusTTF-Italic
bold_italic_font TerminusTTF-BoldItalic
font_size	10.1

# cursor shit
cursor_shape	underline
cursor_blink	-1

# scrollback
scrollback_lines 9999

# mouse
mouse_hide_wait 1.0
detect_urls	yes
url_color	#ff0000
url_style	curly
open_url_with	brave
copy_on_select	yes

# colors
## green
color3  #ff2400
color11 #ff2400
## red 
color2  #c21807
color10 #c21807
# yellow 
color4  #933a16
color12 #933a16
## blue
color5  #ff0800
color13 #ff0800
## magenta
color6  #ff2800
color14 #a45a52
## cyan
color7  #dddddd
color15 #ffffff
